package com.vr.domain;
// Generated 2017-7-25 17:54:49 by Hibernate Tools 4.0.1.Final

/**
 * Answer generated by hbm2java
 */
public class Answer implements java.io.Serializable {

	private Integer id;
	private User user;
	private Question question;
	private String answer;
	private String productname;
	private String producttype;

	public Answer() {
	}

	public Answer(User user, Question question, String answer, String productname, String producttype) {
		this.user = user;
		this.question = question;
		this.answer = answer;
		this.productname = productname;
		this.producttype = producttype;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	public String getProductname() {
		return this.productname;
	}

	public void setProductname(String productname) {
		this.productname = productname;
	}

	public String getProducttype() {
		return this.producttype;
	}

	public void setProducttype(String producttype) {
		this.producttype = producttype;
	}

}
