package com.vr.domain;
// Generated 2017-7-20 15:29:22 by Hibernate Tools 4.3.5.Final

/**
 * Editor generated by hbm2java
 */
public class Editor implements java.io.Serializable {

	private Integer id;
	private Integer password;
	private Integer username;

	public Editor() {
	}

	public Editor(Integer password, Integer username) {
		this.password = password;
		this.username = username;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getPassword() {
		return this.password;
	}

	public void setPassword(Integer password) {
		this.password = password;
	}

	public Integer getUsername() {
		return this.username;
	}

	public void setUsername(Integer username) {
		this.username = username;
	}

}
