package com.vr.domain;
// Generated 2017-7-20 15:29:22 by Hibernate Tools 4.3.5.Final

import com.fasterxml.jackson.annotation.JsonView;
import com.vr.view.MessageLeavingView;

/**
 * MessageResponse generated by hbm2java
 */
public class MessageResponse implements java.io.Serializable {
	@JsonView(MessageLeavingView.Tag.class)
	private Integer id;

	private MessageLeaving messageLeaving;
	@JsonView(MessageLeavingView.Tag.class)
	
	private User user;
	@JsonView(MessageLeavingView.Tag.class)
	private String messageResponse;
	@JsonView(MessageLeavingView.Tag.class)
	private String releasetime;

	public MessageResponse() {
	}

	public MessageResponse(MessageLeaving messageLeaving, User user, String messageResponse, String releasetime) {
		this.messageLeaving = messageLeaving;
		this.user = user;
		this.messageResponse = messageResponse;
		this.releasetime = releasetime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public MessageLeaving getMessageLeaving() {
		return this.messageLeaving;
	}

	public void setMessageLeaving(MessageLeaving messageLeaving) {
		this.messageLeaving = messageLeaving;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getMessageResponse() {
		return this.messageResponse;
	}

	public void setMessageResponse(String messageResponse) {
		this.messageResponse = messageResponse;
	}

	public String getReleasetime() {
		return releasetime;
	}

	public void setReleasetime(String releasetime) {
		this.releasetime = releasetime;
	}



}
