package com.vr.domain;
// Generated 2017-7-20 15:29:22 by Hibernate Tools 4.3.5.Final

/**
 * Profile generated by hbm2java
 */
public class Profile implements java.io.Serializable {

	private ProfileId id;

	public Profile() {
	}

	public Profile(ProfileId id) {
		this.id = id;
	}

	public ProfileId getId() {
		return this.id;
	}

	public void setId(ProfileId id) {
		this.id = id;
	}

}
