package com.vr.domain;
// Generated 2017-7-20 15:29:22 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonView;
import com.vr.view.QuestionView;

/**
 * Question generated by hbm2java
 */
public class Question implements java.io.Serializable {
	@JsonView(QuestionView.Tag.class)
	private Integer id;
	@JsonView(QuestionView.Tag.class)
	private String question;
	@JsonView(QuestionView.Tag.class)
	private String questiontype;
	private Set answers = new HashSet(0);

	public Question() {
	}

	public Question(String question, String questiontype, Set answers) {
		this.question = question;
		this.questiontype = questiontype;
		this.answers = answers;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public String getQuestiontype() {
		return this.questiontype;
	}

	public void setQuestiontype(String questiontype) {
		this.questiontype = questiontype;
	}

	public Set getAnswers() {
		return this.answers;
	}

	public void setAnswers(Set answers) {
		this.answers = answers;
	}

}
