package com.vr.domain;
// Generated 2017-7-22 15:24:21 by Hibernate Tools 4.0.1.Final

/**
 * Thumbsupdown generated by hbm2java
 */
public class Thumbsupdown implements java.io.Serializable {

	private Integer id;
	private String type;
	private Integer upvote;
	private Integer downvote;
	private Integer state;
	


	@Override
	public String toString() {
		return "Thumbsupdown [id=" + id + ", type=" + type + ", upvote=" + upvote + ", downvote=" + downvote
				+ ", state=" + state + "]";
	}

	public Integer getState() {
		return state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public Thumbsupdown() {
	}

	public Thumbsupdown(String type, Integer upvote, Integer downvote) {
		this.type = type;
		this.upvote = upvote;
		this.downvote = downvote;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Integer getUpvote() {
		return this.upvote;
	}

	public void setUpvote(Integer upvote) {
		this.upvote = upvote;
	}

	public Integer getDownvote() {
		return this.downvote;
	}

	public void setDownvote(Integer downvote) {
		this.downvote = downvote;
	}

}
