package com.vr.domain;
// Generated 2017-7-20 15:29:22 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonView;
import com.vr.view.MessageLeavingView;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {
	@JsonView(MessageLeavingView.Tag.class)
	private Integer id;
	private Integer activated;
	private Integer age;
	private Integer banned;
	private String email;
	@JsonView(MessageLeavingView.Tag.class)
	private String nickname;
	private String password;
	private Integer sex;
	private Integer type;
	private String username;
	private Integer votedflag;
	private Set messageLeavings = new HashSet(0);
	private Set answers = new HashSet(0);
	private Set messageResponses = new HashSet(0);
	private String Checkcode;


	public String getCheckcode() {
		return Checkcode;
	}

	public void setCheckcode(String checkcode) {
		Checkcode = checkcode;
	}

	public User() {
	}

	public User(Integer activated, Integer age, Integer banned, String email, String nickname, String password,
			Integer sex, Integer type, String username, Integer votedflag, Set messageLeavings, Set answers,
			Set messageResponses) {
		this.activated = activated;
		this.age = age;
		this.banned = banned;
		this.email = email;
		this.nickname = nickname;
		this.password = password;
		this.sex = sex;
		this.type = type;
		this.username = username;
		this.votedflag = votedflag;
		this.messageLeavings = messageLeavings;
		this.answers = answers;
		this.messageResponses = messageResponses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getActivated() {
		return this.activated;
	}

	public void setActivated(Integer activated) {
		this.activated = activated;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public Integer getBanned() {
		return this.banned;
	}

	public void setBanned(Integer banned) {
		this.banned = banned;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getVotedflag() {
		return this.votedflag;
	}

	public void setVotedflag(Integer votedflag) {
		this.votedflag = votedflag;
	}

	public Set getMessageLeavings() {
		return this.messageLeavings;
	}

	public void setMessageLeavings(Set messageLeavings) {
		this.messageLeavings = messageLeavings;
	}

	public Set getAnswers() {
		return this.answers;
	}

	public void setAnswers(Set answers) {
		this.answers = answers;
	}

	public Set getMessageResponses() {
		return this.messageResponses;
	}

	public void setMessageResponses(Set messageResponses) {
		this.messageResponses = messageResponses;
	}

}
