package com.vr.domain;
// Generated 2017-7-20 15:29:22 by Hibernate Tools 4.3.5.Final

/**
 * VotedUserId generated by hbm2java
 */
public class VotedUserId implements java.io.Serializable {

	private int userid;
	private String name;

	public VotedUserId() {
	}

	public VotedUserId(int userid, String name) {
		this.userid = userid;
		this.name = name;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VotedUserId))
			return false;
		VotedUserId castOther = (VotedUserId) other;

		return (this.getUserid() == castOther.getUserid())
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserid();
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		return result;
	}

}
