package com.vr.domain;
// Generated 2017-7-20 15:29:22 by Hibernate Tools 4.3.5.Final

/**
 * VotedUser generated by hbm2java
 */
public class VotedUser implements java.io.Serializable {

	private VotedUserId id;
	private String type;

	public VotedUser() {
	}

	public VotedUser(VotedUserId id) {
		this.id = id;
	}

	public VotedUser(VotedUserId id, String type) {
		this.id = id;
		this.type = type;
	}

	public VotedUserId getId() {
		return this.id;
	}

	public void setId(VotedUserId id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
